---
- name: Deploy Apache on EC2 instances
  hosts: WEB_SERVERS
  become: yes


  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      
    - name: set timezone to Africa/Lagos
      tags: time
      timezone: name=Africa/Lagos

    - name: install Apache2
      apt:
        name: apache2
        state: present

    - name: remove index.html
      file:
        path: /var/www/html/index.html
        state: absent

    - name: use the printf script
      shell: |
        sudo echo "<h1>Welcome this is my hostname:</h1>" >> /var/www/html/index.html
        sudo echo "<p>$(hostname -f)</p>" >> /var/www/html/index.html
      notify: restart Apache
 
    - name: Start Apache2 service
      service:
        name: apache2
        state: started
        enabled: yes
