---
# tasks file for key_pair
- name: Create a Key Pair to be used by the EC2 for ssh authentication
  amazon.aws.ec2_key:
    name: "{{ key_pair_name }}"
    region: "{{ region }}"
    file_name: ./{{ key_pair_name }}.pem
  register: aws_ec2_key_pair